"""
Inline Diff Generator

Generates track-changes style output for course editorial review.
Uses markdown formatting that can be pasted into Word for Track Changes view.

Output format:
    ~~original~~ **suggested** [Explanation: reason. Category: category]

This format allows Kim to:
1. See changes inline in context
2. Search for ~~ or ** to find all changes
3. Copy/paste into Word where formatting is preserved
"""
import os
import re
from typing import List, Dict, Optional
from datetime import datetime

# Add tools directory to path for imports
import sys
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.insert(0, script_dir)

from editorial_models import ValidationResult, EditorialIssue
from course_models import map_category


# =============================================================================
# Category Mapping for Kim's 4 Categories
# =============================================================================

def get_kim_category(rule_id: str) -> str:
    """
    Map rule ID to Kim's 4 categories.

    Categories:
    - Cisco Style Guide
    - Acronyms
    - Technical Terms
    - Grammar & Punctuation
    """
    # Map rule prefixes to categories
    if rule_id.startswith('ACRONYM'):
        return "Acronyms"
    elif rule_id.startswith('PRODUCT') or rule_id.startswith('CODE'):
        return "Technical Terms"
    elif rule_id.startswith('TERM') or rule_id.startswith('HEADING') or rule_id.startswith('GUI'):
        return "Cisco Style Guide"
    elif rule_id.startswith('PUNCT') or rule_id.startswith('CMS') or rule_id.startswith('STRUCT'):
        return "Grammar & Punctuation"
    else:
        return "Grammar & Punctuation"


def get_short_rationale(issue: EditorialIssue) -> str:
    """
    Extract a concise rationale from the issue message.
    Removes redundant prefixes and keeps it brief.
    """
    msg = issue.message

    # Remove common prefixes
    prefixes = [
        "Consider ",
        "Found: ",
        "Detected: ",
        "Use ",
        "Change ",
    ]
    for prefix in prefixes:
        if msg.lower().startswith(prefix.lower()):
            msg = msg[len(prefix):]
            break

    # Truncate if too long
    if len(msg) > 60:
        msg = msg[:57] + "..."

    return msg


# =============================================================================
# Inline Diff Generation
# =============================================================================

def generate_inline_diff(
    markdown_content: str,
    result: ValidationResult,
    course_name: str = "Course"
) -> str:
    """
    Generate inline diff output showing changes in track-changes style.

    Args:
        markdown_content: Original converted markdown content
        result: ValidationResult with all issues
        course_name: Name of the course for header

    Returns:
        Markdown string with inline changes marked up
    """
    lines = []

    # Header
    lines.append(f"# Inline Editorial Review: {course_name}")
    lines.append("")
    lines.append("**Instructions**: Search for `~~` to find deletions and `**` to find additions.")
    lines.append("Copy this document into Word to see Track Changes formatting.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary stats
    score = result.quality_score
    if score:
        lines.append(f"**Total Changes**: {score.total_issues} "
                    f"(Auto-fix: {score.safe_count}, Review: {score.review_count}, "
                    f"Questions: {score.query_count})")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Apply changes to content
    modified_content = apply_inline_changes(markdown_content, result.issues)
    lines.append(modified_content)

    # Footer with legend
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Change Legend")
    lines.append("")
    lines.append("| Markup | Meaning |")
    lines.append("|--------|---------|")
    lines.append("| ~~text~~ | Text to remove (strikethrough) |")
    lines.append("| **text** | Text to add (bold) |")
    lines.append("| [Explanation: ...] | Rationale for change |")
    lines.append("")
    lines.append(f"*Generated by Course AI Editor on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    return '\n'.join(lines)


def apply_inline_changes(content: str, issues: List[EditorialIssue]) -> str:
    """
    Apply inline markup to content showing all changes.

    Changes are applied in reverse order (by position) to maintain
    correct offsets as we modify the string.

    Args:
        content: Original markdown content
        issues: List of editorial issues with suggested fixes

    Returns:
        Modified content with inline change markup
    """
    # Filter to issues that have both original text and a suggestion
    applicable_issues = [
        i for i in issues
        if i.suggested_fix and i.original_text and i.suggested_fix != i.original_text
    ]

    # Sort by absolute_offset in reverse order
    # This ensures we apply changes from end to start to maintain offsets
    sorted_issues = sorted(applicable_issues, key=lambda x: x.absolute_offset, reverse=True)

    # Track which offsets we've already modified (to handle duplicates)
    modified_offsets = set()

    for issue in sorted_issues:
        # Skip if we've already modified this position
        if issue.absolute_offset in modified_offsets:
            continue

        # Find the text in content
        # Use absolute_offset if available, otherwise search
        if issue.absolute_offset > 0:
            start = issue.absolute_offset
            end = start + len(issue.original_text)

            # Verify the text matches
            if content[start:end] != issue.original_text:
                # Text doesn't match at expected position, try to find it
                start = content.find(issue.original_text, max(0, start - 50))
                if start == -1:
                    continue
                end = start + len(issue.original_text)
        else:
            # Search for the text
            start = content.find(issue.original_text)
            if start == -1:
                continue
            end = start + len(issue.original_text)

        # Build the inline change markup
        category = get_kim_category(issue.rule_id)
        rationale = get_short_rationale(issue)

        # Format: ~~original~~ **suggested** [Explanation: reason. Category: cat]
        markup = f"~~{issue.original_text}~~ **{issue.suggested_fix}** [Explanation: {rationale}. Category: {category}]"

        # Apply the change
        content = content[:start] + markup + content[end:]

        # Mark this offset as modified
        modified_offsets.add(issue.absolute_offset)

    # Also add QUERY issues as comments (no change, just question)
    query_issues = [i for i in issues if i.fix_type == 'QUERY']
    for issue in sorted(query_issues, key=lambda x: x.absolute_offset, reverse=True):
        if issue.absolute_offset in modified_offsets:
            continue

        if issue.absolute_offset > 0:
            start = issue.absolute_offset
            end = start + len(issue.original_text)

            if content[start:end] == issue.original_text:
                category = get_kim_category(issue.rule_id)
                markup = f"{issue.original_text} [QUESTION: {issue.message}. Category: {category}]"
                content = content[:start] + markup + content[end:]
                modified_offsets.add(issue.absolute_offset)

    return content


# =============================================================================
# Alternative: Change List with Context
# =============================================================================

def generate_change_list_with_context(
    result: ValidationResult,
    course_name: str = "Course"
) -> str:
    """
    Generate a change list showing each change with surrounding context.

    This is an alternative format that shows:
    - Line number
    - Context before/after
    - The change in track-changes format
    - Category and rationale

    Args:
        result: ValidationResult with all issues
        course_name: Name of the course for header

    Returns:
        Markdown string with change list
    """
    lines = []

    # Header
    lines.append(f"# Editorial Change List: {course_name}")
    lines.append("")

    # Summary
    score = result.quality_score
    if score:
        lines.append(f"**Total Issues**: {score.total_issues}")
        lines.append(f"- Auto-fixable (SAFE): {score.safe_count}")
        lines.append(f"- Needs Review (REVIEW): {score.review_count}")
        lines.append(f"- Questions (QUERY): {score.query_count}")
        lines.append("")

    # Group by category
    by_category: Dict[str, List[EditorialIssue]] = {
        'Cisco Style Guide': [],
        'Acronyms': [],
        'Technical Terms': [],
        'Grammar & Punctuation': []
    }

    for issue in result.issues:
        category = get_kim_category(issue.rule_id)
        by_category[category].append(issue)

    # Output each category
    for category, issues in by_category.items():
        if not issues:
            continue

        lines.append(f"## {category} ({len(issues)} issues)")
        lines.append("")

        for issue in sorted(issues, key=lambda x: x.line_number):
            lines.append(f"### Line {issue.line_number}")
            lines.append("")

            # Show context with change inline
            context_before = issue.context_before or ""
            context_after = issue.context_after or ""

            if issue.suggested_fix and issue.original_text != issue.suggested_fix:
                # Show as inline change
                change_display = f"...{context_before}~~{issue.original_text}~~ **{issue.suggested_fix}**{context_after}..."
            else:
                # Show as question
                change_display = f"...{context_before}**{issue.original_text}**{context_after}..."

            lines.append(f"> {change_display}")
            lines.append("")

            # Type indicator
            type_emoji = {"SAFE": "🟢", "REVIEW": "🟡", "QUERY": "🔴"}.get(issue.fix_type, "⚪")
            lines.append(f"{type_emoji} **{issue.fix_type}**: {issue.message}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by Course AI Editor on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    return '\n'.join(lines)


# =============================================================================
# CLI Interface
# =============================================================================

if __name__ == '__main__':
    import argparse
    import json

    parser = argparse.ArgumentParser(
        description='Generate inline diff from validation JSON'
    )
    parser.add_argument('json_file', help='Path to validation JSON file')
    parser.add_argument('markdown_file', help='Path to converted markdown file')
    parser.add_argument('--output', '-o', help='Output file (default: stdout)')
    parser.add_argument('--list-format', action='store_true',
                        help='Use change list format instead of inline diff')

    args = parser.parse_args()

    # Load validation result
    with open(args.json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Load markdown content
    with open(args.markdown_file, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    # Reconstruct ValidationResult
    from editorial_models import QualityScore

    result = ValidationResult(tutorial_folder=data.get('tutorial_folder', 'Unknown'))
    result.files_processed = data.get('files_processed', [])
    result.processing_time_ms = data.get('processing_time_ms', 0)

    # Reconstruct issues
    for issue_data in data.get('issues', []):
        issue = EditorialIssue(
            rule_id=issue_data['rule_id'],
            file_path=issue_data['file_path'],
            line_number=issue_data['line_number'],
            original_text=issue_data['original_text'],
            fix_type=issue_data['fix_type'],
            message=issue_data['message'],
            confidence=issue_data['confidence'],
            suggested_fix=issue_data.get('suggested_fix'),
            context_before=issue_data.get('context_before', ''),
            context_after=issue_data.get('context_after', ''),
            absolute_offset=issue_data.get('absolute_offset', 0)
        )
        result.add_issue(issue)

    result.calculate_score()

    # Generate output
    course_name = os.path.splitext(os.path.basename(args.markdown_file))[0]

    if args.list_format:
        output = generate_change_list_with_context(result, course_name)
    else:
        output = generate_inline_diff(markdown_content, result, course_name)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(output)
        print(f"Output written to: {args.output}")
    else:
        print(output)
